spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: callOrderFallback
                fallbackUri: forward:/fallback/order

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filers:
            - name: CircuitBreaker
              args:
                name: callPaymentFallback
                fallbackUri: forward:/fallback/payment

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name : callUserFallback
                fallbackUri : forward:/fallback/user
#          filers:
#            - name: CircuitBreaker
#              args:
#                name: callUserFallback
#                fallbackUri: forward:/fallback/user

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          filers:
            - name: CircuitBreaker
              args:
                name: callIdentityFallback
                fallbackUri: forward:/fallback/identity


    config:
      import-check:
        enabled: false

server:
  port: 9090


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway"